version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - redis

  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine 
    command: redis-server
    expose:
        - 6379
    ports:
        - '6379:6379'

  worker:
      build: .
      command: celery -A youtube_video worker --loglevel=info
      volumes:
        - .:/app
      depends_on:
        - redis